#166495422 Create a home page.
andela/ah-kgl-avengers-frontend pull request #9
Opened 2019-06-11 11:44 UTC by niyobobo

### What does this PR do?

### Description of Task to be completed?

### How should this be manually tested?

### Any background context you want to provide?

### What are the relevant pivotal tracker stories?

### Screenshots (if appropriate)

### Questions:

2019-06-11 18:30 UTC, avpaul commented
@niyobobo  In the PR description, there is a typo:
`Install dependencies by run npm install script.` should be `Install dependencies by running npm install script.`

2019-06-11 18:48 UTC, avpaul requested changes
Great work @niyobobo 👏 👏  But the design breaks on smaller devices, which I think is because of the footer. Plus the second navigation, the one with categories should be made responsive(consider making it a dropdown).

2019-06-11 18:48 UTC, niyobobo commented
> @niyobobo In the PR description, there is a typo:
> `Install dependencies by run npm install script.` should be `Install dependencies by running npm install script.`

Thank you @avpaul for the feedback. I have fixed this.

2019-06-12 06:40 UTC, ezkemboi requested changes
I have left some review on the PR

2019-06-12 06:40 UTC, me-x-mi commented on src/components/functional/footer.jsx
> +const Footer = () => (
The footer is still not responsive. 
![Screen Shot 2019-06-12 at 09 36 58](https://user-images.githubusercontent.com/48981919/59328754-df230080-8cf5-11e9-81b7-2427bd93cb4c.png)

2019-06-12 06:40 UTC, me-x-mi commented on src/components/functional/navBar.jsx
> +          <NavbarBrand className="nav-logo">
I would love this navbar logo to be clickable. When I click navbar, it takes me to `/` page, no matter the page I am. 
Make the whole logo image and text clickable and redirect always to homepage.

2019-06-12 06:45 UTC, me-x-mi commented
Also, please update screenshots section of the PR @niyobobo. Thank you.

2019-06-12 08:29 UTC, ezkemboi approved these changes
Changes made are satisfactory on my side.

2019-06-12 11:27 UTC, avpaul approved these changes

2019-06-12 11:27 UTC, fridolinho approved these changes

2019-06-12 11:40 UTC, merged